apiVersion: apps/v1
kind: Deployment
metadata:
  name: sc-web
  namespace: ostis-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sc-web
  template:
    metadata:
      labels:
        app: sc-web
    spec:
      containers:
      - name: sc-web
        image: ostis/sc-web:0.9.0
        command: ["/usr/bin/tini", "--", "/sc-web/scripts/docker_entrypoint.sh"]
        args:
        - "--server-host=machine"
        - "--server-port=8090"
        - "--public-url=ws://localhost:30081/ws_json"
        - "--host=0.0.0.0"
        - "--port=8000"
        env:
        - name: SC_SERVER
          value: "ws://machine:8090/ws_json"
        - name: SC_SERVER_HOST
          value: "machine"
        - name: SC_SERVER_PORT
          value: "8090"
        - name: SECRET_KEY
          value: "3rVRe2LGTg+QYpGWEKihiGzDuMFhMkEZt5eZvZl9Bmc="
        ports:
        - containerPort: 8000