apiVersion: v1
kind: ConfigMap
metadata:
  name: sc-machine-config
  namespace: ostis-system
data:
  sc-machine.ini: |
    [sc-memory]
    max_loaded_segments = 1000

    limit_max_threads_by_max_physical_cores = true
    max_events_and_agents_threads = 32

    dump_memory = false
    dump_memory_period = 3600
    dump_memory_statistics = false
    dump_memory_statistics_period = 1800

    storage = ./kb.bin

    log_type = Console
    log_file = ./sc-memory.log
    log_level = Info

    init_memory_generated_upload = false
    init_memory_generated_structure = result_structure

    user_mode = false

    max_strings_channels = 1000
    max_strings_channel_size = 100000
    max_searchable_string_size = 1000
    term_separators = " _"
    search_by_substring = true

    [sc-server]
    host = 0.0.0.0
    port = 8090

    parallel_actions = true

    log_type = File
    log_file = ./sc-server.log
    log_level = Info

    [sc-builder]
    input = kb
    output = kb.bin
